from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path

from .models import Artifact, BuildSeed, stable_id


def slugify(value: str) -> str:
    value = value.lower().strip()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value or "mined-artifact"


def package_name(repo_name: str) -> str:
    return slugify(repo_name).replace("-", "_")


def build_seed_from_artifact(artifact: Artifact) -> BuildSeed:
    return BuildSeed(
        seed_id=stable_id("seed", artifact.artifact_id),
        block_id=artifact.block_id,
        artifact_id=artifact.artifact_id,
        thesis=f"Build from artifact: {artifact.title}",
        evidence=artifact.evidence,
        recommended_first_files=[
            "README.md",
            "docs/architecture.md",
            "data/build_seed.json",
            "src/<package>/__init__.py",
            "src/<package>/cli.py",
            "tests/test_smoke.py",
        ],
        falsification_check=(
            "The generated repo must install, run its CLI, and pass its smoke test using only the "
            "evidence in the BuildSeed."
        ),
    )


def render_repo(seed: BuildSeed, artifact: Artifact, output_dir: str | Path, force: bool = False) -> Path:
    out = Path(output_dir)
    if out.exists() and any(out.iterdir()) and not force:
        raise FileExistsError(f"output directory is not empty: {out}")
    out.mkdir(parents=True, exist_ok=True)
    repo_name = slugify(artifact.title)
    pkg = package_name(repo_name)
    files = {
        ".gitignore": "__pycache__/\n*.py[cod]\n.pytest_cache/\n.venv/\ndist/\n*.egg-info/\n",
        "README.md": _readme(seed, artifact, repo_name),
        "pyproject.toml": _pyproject(repo_name, pkg),
        "docs/architecture.md": _architecture(seed, artifact),
        "data/build_seed.json": json.dumps(seed.to_dict(), indent=2, sort_keys=True) + "\n",
        f"src/{pkg}/__init__.py": f"\"\"\"Runnable repo generated from Data Mine artifact {artifact.artifact_id}.\"\"\"\n\n__version__ = '0.1.0'\n",
        f"src/{pkg}/cli.py": _cli_py(pkg),
        "tests/test_smoke.py": _test_py(pkg),
    }
    for rel, content in files.items():
        path = out / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    subprocess.run(["git", "init"], cwd=out, check=True, capture_output=True, text=True)
    subprocess.run(["git", "add", "."], cwd=out, check=True, capture_output=True, text=True)
    subprocess.run(
        ["git", "commit", "-m", "Initial runnable repo from Data Mine artifact"],
        cwd=out,
        check=True,
        capture_output=True,
        text=True,
    )
    return out


def _readme(seed: BuildSeed, artifact: Artifact, repo_name: str) -> str:
    evidence_lines = "\n".join(
        f"- `{e.record_id}`: {e.snippet} ({e.reason})" for e in seed.evidence[:8]
    )
    return f"""# {artifact.title}

Runnable repo generated from a Data Mine artifact.

## Source

- block: `{seed.block_id}`
- artifact: `{seed.artifact_id}`
- artifact kind: `{artifact.kind}`
- miner: `{artifact.miner}`
- score: `{artifact.score.value}`

## Thesis

{seed.thesis}

## Evidence

{evidence_lines}

## Run

```bash
python -m venv .venv
source .venv/bin/activate
pip install -e '.[dev]'
pytest -q
{repo_name} status
```

## Falsification check

{seed.falsification_check}
"""


def _pyproject(repo_name: str, pkg: str) -> str:
    return f"""[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{repo_name}"
version = "0.1.0"
description = "Runnable build seed generated by Data Mine."
readme = "README.md"
requires-python = ">=3.11"
license = {{text = "MIT"}}
dependencies = []

[project.optional-dependencies]
dev = ["pytest>=8"]

[project.scripts]
{repo_name} = "{pkg}.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
"""


def _architecture(seed: BuildSeed, artifact: Artifact) -> str:
    return f"""# Architecture

This repo is intentionally small. It proves that a mined artifact can become a runnable build surface.

## Input

Data Mine block `{seed.block_id}` produced artifact `{artifact.artifact_id}`.

## Current runnable surface

- `data/build_seed.json` stores the t0 build input.
- CLI `status` prints the seed summary.
- Smoke test verifies the seed exists and the CLI loads it.

## Next implementation step

Replace the generated CLI with the first real mechanism implied by the evidence. If no mechanism can be named, the artifact was not ready to promote.
"""


def _cli_py(pkg: str) -> str:
    return """from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_seed() -> dict:
    root = Path(__file__).resolve().parents[2]
    return json.loads((root / "data" / "build_seed.json").read_text(encoding="utf-8"))


def cmd_status(_: argparse.Namespace) -> None:
    seed = load_seed()
    print(json.dumps({
        "status": "runnable",
        "seed_id": seed["seed_id"],
        "block_id": seed["block_id"],
        "artifact_id": seed["artifact_id"],
        "evidence_count": len(seed.get("evidence", [])),
        "thesis": seed["thesis"],
    }, indent=2, sort_keys=True))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(required=True)
    status = sub.add_parser("status")
    status.set_defaults(func=cmd_status)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = build_parser().parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
"""


def _test_py(pkg: str) -> str:
    return f"""import json
import subprocess
import sys
from pathlib import Path

from {pkg}.cli import load_seed


def test_seed_exists_and_has_evidence():
    seed = load_seed()
    assert seed["seed_id"]
    assert seed["artifact_id"]
    assert seed["evidence"]


def test_cli_status_runs():
    result = subprocess.run(
        [sys.executable, "-m", "{pkg}.cli", "status"],
        cwd=Path(__file__).resolve().parents[1],
        env={{**__import__("os").environ, "PYTHONPATH": "src"}},
        check=True,
        capture_output=True,
        text=True,
    )
    payload = json.loads(result.stdout)
    assert payload["status"] == "runnable"
    assert payload["evidence_count"] > 0
"""
